# Generated by Django 6.0.3 on 2026-04-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(default='Anonimo', max_length=120)),
                (
                    'categoria',
                    models.CharField(
                        choices=[
                            ('Recomendacion', 'Recomendacion Medica'),
                            ('Testimonio', 'Testimonio de Vida'),
                            ('Opinion', 'Opinion'),
                            ('Duda', 'Duda / Consulta'),
                        ],
                        default='Testimonio',
                        max_length=32,
                    ),
                ),
                ('titulo', models.CharField(max_length=180)),
                ('contenido', models.TextField()),
                ('likes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                (
                    'asunto',
                    models.CharField(
                        choices=[
                            ('General', 'Consulta General'),
                            ('Aliado', 'Quiero ser Institucion Aliada'),
                            ('Prensa', 'Contacto de Prensa'),
                            ('Denuncia', 'Reporte / Sugerencia'),
                        ],
                        default='General',
                        max_length=24,
                    ),
                ),
                ('mensaje', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
