# Generated by Django 6.0.3 on 2026-06-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blogpost_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                (
                    'nivel',
                    models.CharField(
                        choices=[('I', 'Nivel I'), ('II', 'Nivel II'), ('III', 'Nivel III')],
                        max_length=3,
                    ),
                ),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(default='', max_length=120)),
                ('telefono', models.CharField(max_length=40)),
                ('telefono_emergencia', models.CharField(blank=True, default='', max_length=40)),
                ('horario', models.CharField(blank=True, default='', max_length=120)),
                ('ambulancia_disponible', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nivel', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PanicAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(db_index=True, max_length=64)),
                ('symptom', models.CharField(blank=True, default='', max_length=120)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    'status',
                    models.CharField(
                        choices=[('open', 'Abierta'), ('acknowledged', 'Reconocida'), ('closed', 'Cerrada')],
                        default='open',
                        max_length=16,
                    ),
                ),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdolescentConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(db_index=True, max_length=64)),
                (
                    'topic',
                    models.CharField(
                        choices=[
                            ('contracepcion', 'Anticoncepción'),
                            ('prevencion', 'Prevención'),
                            ('ciclo', 'Ciclo menstrual'),
                            ('otro', 'Otra consulta'),
                        ],
                        default='otro',
                        max_length=24,
                    ),
                ),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, default='')),
                (
                    'status',
                    models.CharField(
                        choices=[('pending', 'Pendiente'), ('answered', 'Respondida'), ('closed', 'Cerrada')],
                        default='pending',
                        max_length=16,
                    ),
                ),
                ('responder_name', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
