# Generated by Django 6.0.3 on 2026-06-08 00:00

from django.db import migrations


def seed_demo_health_centers(apps, schema_editor):
    HealthCenter = apps.get_model('api', 'HealthCenter')

    if HealthCenter.objects.exists():
        return

    HealthCenter.objects.bulk_create([
        HealthCenter(
            nombre='Centro de Salud San Martín',
            nivel='I',
            direccion='Av. Principal 123',
            ciudad='Cochabamba',
            telefono='+591 4 444 1111',
            telefono_emergencia='+591 4 444 1112',
            horario='Lun a sáb 08:00 - 20:00',
            ambulancia_disponible=True,
            latitude='-17.381300',
            longitude='-66.156800',
        ),
        HealthCenter(
            nombre='Hospital Materno Regional',
            nivel='II',
            direccion='Calle Salud y Vida 240',
            ciudad='La Paz',
            telefono='+591 2 222 4200',
            telefono_emergencia='+591 2 222 4201',
            horario='24 horas',
            ambulancia_disponible=True,
            latitude='-16.489700',
            longitude='-68.119300',
        ),
        HealthCenter(
            nombre='Red Integrada Sur',
            nivel='III',
            direccion='Zona Sur, Manzano 4',
            ciudad='Santa Cruz',
            telefono='+591 3 333 9080',
            telefono_emergencia='+591 3 333 9081',
            horario='24 horas',
            ambulancia_disponible=True,
            latitude='-17.783300',
            longitude='-63.182100',
        ),
        HealthCenter(
            nombre='Hospital Municipal Cochabamba',
            nivel='II',
            direccion='Av. Aniceto Arce 100',
            ciudad='Cochabamba',
            telefono='+591 4 444 2100',
            telefono_emergencia='+591 4 444 2101',
            horario='24 horas',
            ambulancia_disponible=True,
            latitude='-17.393400',
            longitude='-66.157000',
        ),
        HealthCenter(
            nombre='Hospital Municipal Santa Cruz',
            nivel='II',
            direccion='Barrio Equipetrol Norte',
            ciudad='Santa Cruz',
            telefono='+591 3 333 2200',
            telefono_emergencia='+591 3 333 2201',
            horario='24 horas',
            ambulancia_disponible=True,
            latitude='-17.781700',
            longitude='-63.181000',
        ),
        HealthCenter(
            nombre='Hospital de la Mujer',
            nivel='III',
            direccion='Av. América y Pando',
            ciudad='Cochabamba',
            telefono='+591 4 401 0000',
            telefono_emergencia='+591 4 401 0001',
            horario='24 horas',
            ambulancia_disponible=True,
            latitude='-17.384600',
            longitude='-66.169400',
        ),
        HealthCenter(
            nombre='Centro Integral de Salud Warnes',
            nivel='I',
            direccion='Av. Principal 450',
            ciudad='Warnes',
            telefono='+591 3 333 7780',
            telefono_emergencia='+591 3 333 7781',
            horario='Lun a dom 07:00 - 22:00',
            ambulancia_disponible=False,
            latitude='-17.507000',
            longitude='-63.167000',
        ),
    ])


def remove_demo_health_centers(apps, schema_editor):
    HealthCenter = apps.get_model('api', 'HealthCenter')
    HealthCenter.objects.filter(nombre__in=[
        'Centro de Salud San Martín',
        'Hospital Materno Regional',
        'Red Integrada Sur',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_public_sector_modules'),
    ]

    operations = [
        migrations.RunPython(seed_demo_health_centers, remove_demo_health_centers),
    ]
