# Generated by GitHub Copilot on 2026-06-10

from django.db import migrations


def seed_public_sector_interactions(apps, schema_editor):
    PanicAlert = apps.get_model('api', 'PanicAlert')
    AdolescentConsultation = apps.get_model('api', 'AdolescentConsultation')

    if not PanicAlert.objects.exists():
        PanicAlert.objects.bulk_create([
            PanicAlert(
                session_token='demoalert000000000000000000000000000000000000000000000000000001',
                symptom='hemorragia',
                latitude='-16.503210',
                longitude='-68.132450',
                status='open',
                note='Alerta de demostracion para monitoreo inicial.',
            ),
            PanicAlert(
                session_token='demoalert000000000000000000000000000000000000000000000000000002',
                symptom='vision_borrosa',
                latitude='-17.389500',
                longitude='-66.156700',
                status='acknowledged',
                note='La coordinacion local ya fue notificada.',
            ),
        ])

    if not AdolescentConsultation.objects.exists():
        AdolescentConsultation.objects.bulk_create([
            AdolescentConsultation(
                session_token='democonsulta000000000000000000000000000000000000000000000000001',
                topic='contracepcion',
                question='Quiero saber que metodo anticonceptivo me conviene si es mi primera consulta.',
                answer='',
                status='pending',
                responder_name='',
            ),
            AdolescentConsultation(
                session_token='democonsulta000000000000000000000000000000000000000000000000002',
                topic='prevencion',
                question='Tuve una relacion sin proteccion y no se que hacer en las primeras 24 horas.',
                answer='Busca atencion en un centro de salud dentro de las primeras 72 horas para valorar anticoncepcion de emergencia y consejeria.',
                status='answered',
                responder_name='Equipo juvenil',
            ),
        ])


def remove_public_sector_interactions(apps, schema_editor):
    PanicAlert = apps.get_model('api', 'PanicAlert')
    AdolescentConsultation = apps.get_model('api', 'AdolescentConsultation')

    PanicAlert.objects.filter(session_token__startswith='demoalert').delete()
    AdolescentConsultation.objects.filter(session_token__startswith='democonsulta').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_blogpost_id_alter_contactmessage_id_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_public_sector_interactions, remove_public_sector_interactions),
    ]