# Generated by Django 6.0.6 on 2026-06-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_seed_public_sector_interactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='categoria',
            field=models.CharField(choices=[('Recomendacion', 'Recomendacion Medica'), ('Testimonio', 'Testimonio de Vida'), ('Opinion', 'Opinion'), ('Duda', 'Duda / Consulta'), ('Noticia', 'Noticia'), ('Publicacion', 'Publicacion')], default='Testimonio', max_length=32),
        ),
    ]
