# Generated by Django 6.0.6 on 2026-06-11 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_blogpost_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearMissRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_age', models.PositiveIntegerField()),
                ('gestational_age', models.PositiveIntegerField(help_text='Edad gestacional en semanas')),
                ('condition', models.CharField(choices=[('hemorrhage', 'Hemorragia severa'), ('hypertension', 'Trastorno hipertensivo severo (Preeclampsia/Eclampsia)'), ('sepsis', 'Infección sistémica severa / Sepsis'), ('other', 'Otra complicación severa')], max_length=24)),
                ('delay_1_decision', models.BooleanField(default=False, verbose_name='Demora 1: Decisión')),
                ('delay_1_details', models.TextField(blank=True, default='', help_text='Demora en tomar la decisión de buscar ayuda (e.g. desconocimiento, barreras culturales)')),
                ('delay_2_transport', models.BooleanField(default=False, verbose_name='Demora 2: Transporte')),
                ('delay_2_details', models.TextField(blank=True, default='', help_text='Demora en llegar al centro de salud (e.g. distancia, falta de transporte, mal estado de vías)')),
                ('delay_3_care', models.BooleanField(default=False, verbose_name='Demora 3: Atención')),
                ('delay_3_details', models.TextField(blank=True, default='', help_text='Demora en recibir atención oportuna y de calidad (e.g. falta de personal, insumos, burocracia)')),
                ('survival_status', models.CharField(choices=[('survived', 'Sobrevivió'), ('deceased', 'Falleció')], default='survived', max_length=24)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('health_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.healthcenter')),
            ],
            options={
                'verbose_name': 'Registro Near-Miss',
                'verbose_name_plural': 'Registros Near-Miss',
                'ordering': ['-created_at'],
            },
        ),
    ]
